### ISSUE TITLE
Rotate metrics tsv

### ISSUE THREAD

**Issue by maxwofford** [hackclub/metrics#32]
@zachlatta What if we rotated the tsv so a new day added changes only  one line instead of every line?

**Comment by maxwofford** [comment]
@zachlatta Thoughts?

**Comment by zachlatta** [comment]
Oh whoops, yeah. Sorry for the delay on this.

Good call. Let's move this to https://github.com/hackclub/slack-stats-collector.

**Comment by zachlatta** [comment]
This issue was moved to hackclub/slack-stats-collector#2
